version: '3'
# docker-composeの書式のバージョンを指定します。(原則、最新を指定する)

services:
  api:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/api/
    ports:
      - 3001:3000
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  front:
    build: ./frontend/
    volumes:
      - ./frontend/app:/front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mysql_data:
